version: '3.8'

services:
  trainer:
    build: .
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./data:/app/data
    environment:
      - MLFLOW_TRACKING_URI=file:/mlflow/mlruns
    command: python train.py

  promoter:
    build: .
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:/mlflow/mlruns
    command: python promote.py

  inference-api:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - MLFLOW_TRACKING_URI=file:/mlflow/mlruns
      - MODEL_PATH=models:/transformer_load_forecast@production
    command: >
      gunicorn inference:app --bind 0.0.0.0:5000 --workers 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
