version: '3.8'
services:
  inference-api:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:/mlflow/mlruns
    command: >
      gunicorn inference:app
      --bind 0.0.0.0:5000
      --workers 2