$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: ML pipeline with training, promotion, and prediction
compute: azureml:transformer-load-compute

jobs:

  train_transformer_load_model:
    type: command
    component: file:./train.yml
    outputs:
      logged_model: {type: mlflow_model}

  promote_transformer_load_model:
    type: command
    component: file:./promote.yml
    inputs:
      model_input: ${{parent.jobs.train_job.outputs.logged_model}}
    outputs:
      promoted_model: {type: mlflow_model}

  predict_transformer_overload:
    type: command
    component: file:./predict.yml
    inputs:
      model_input: ${{parent.jobs.promote_job.outputs.promoted_model}}
    outputs:
      predictions: {type: uri_folder}
