$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: ML pipeline with training, promotion, and prediction
compute: azureml:transformer-load-compute

jobs:

  train_job:
    type: command
    component: file:./train.yml
    outputs:
      model_output: {type: uri_folder}

  promote_job:
    type: command
    component: file:./promote.yml
    inputs:
      model_input: ${{parent.jobs.train_job.outputs.model_output}}
    outputs:
      promoted_model: {type: uri_folder}

  predict_job:
    type: command
    component: file:./predict.yml
    inputs:
      model_input: ${{parent.jobs.promote_job.outputs.promoted_model}}
    outputs:
      predictions: {type: uri_folder}
