$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: Train Model
version: 1
type: command

inputs: {}
outputs:
  logged_model:
    type: mlflow_model
    mode: rw_mount

environment:
  image: transformerloadacr.azurecr.io/transformer-load-image:latest

code: .
command: >-
  python -u train.py