$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: Train Model
version: 1
type: command

inputs: {}
outputs:
  model_output:
    type: uri_folder

environment:
  image: transformerloadacr.azurecr.io/transformer-load-image:latest

code: ./src
command: >-
  python train.py