name: Train and Deploy ML Model

on:
  push:
    branches: [main]

jobs:
  train-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      ACR_NAME: transformer-load-acr
      IMAGE_NAME: transformer-load-image
      IMAGE_TAG: latest
      FULL_IMAGE: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      RESOURCE_GROUP: transformer-load-rg
      WORKSPACE_NAME: transformer-load-ws

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Build Docker image
        run: docker build -t $FULL_IMAGE .

      - name: Push Docker image to ACR
        run: docker push $FULL_IMAGE

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-ml-deploy

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./terraform-ml-deploy

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform-ml-deploy

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform-ml-deploy

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform-ml-deploy

      - name: Wait for role assignment propagation
        run: sleep 60

      - name: Confirm Azure ML workspace
        run: az ml workspace show --name ${{ env.WORKSPACE_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}

      - name: Submit Azure ML pipeline job
        run: |
          az ml job create --file pipeline.yml \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --workspace-name ${{ env.WORKSPACE_NAME }}